//
//  mcClippyTests.swift
//  mcClippyTests
//
//  Created by Gordon van Straaten on 11/05/2026.
//

import AppKit
import Carbon
import Foundation
import SwiftData
import Testing
@testable import mcClippy

@Suite(.serialized)
struct mcClippyTests {
    @Test func encryptionRoundTripsData() throws {
        let original = Data("token-value-that-should-round-trip".utf8)
        let sealed = EncryptionService.seal(original)

        #expect(sealed != nil)
        #expect(sealed.flatMap(EncryptionService.open) == original)
    }

    @Test func sensitivePreviewIsStoredAsPlaceholder() {
        let snapshot = ClipboardSnapshot(
            type: .text,
            preview: "password=correct-horse-battery-staple",
            data: Data("password=correct-horse-battery-staple".utf8),
            contentHash: "hash",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            isSensitive: true,
            sizeBytes: 37
        )

        #expect(PasteboardSerializer.storedPreview(for: snapshot) == PasteboardSerializer.sensitivePlaceholder)
    }

    @Test func concealedPasteboardContentIsCapturedAsSensitive() {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(UUID().uuidString))
        pasteboard.clearContents()
        pasteboard.setString("Tr0ub4dor&3", forType: .string)
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))

        let snapshot = PasteboardSerializer.snapshot(from: pasteboard)

        #expect(snapshot?.preview == "Tr0ub4dor&3")
        #expect(snapshot?.isSensitive == true)
        #expect(snapshot.map(PasteboardSerializer.storedPreview(for:)) == PasteboardSerializer.sensitivePlaceholder)
    }

    @Test func revealedSensitivePreviewUsesDecryptedData() throws {
        let secret = "password=correct-horse-battery-staple"
        let data = Data(secret.utf8)
        let item = Item(
            type: .text,
            plainTextPreview: PasteboardSerializer.sensitivePlaceholder,
            dataBlob: EncryptionService.seal(data),
            contentHash: "hash",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            isSensitive: true,
            sizeBytes: data.count,
            isEncrypted: true
        )

        #expect(PasteboardSerializer.displayPreview(for: item, revealingSensitive: false) == PasteboardSerializer.sensitivePlaceholder)
        #expect(PasteboardSerializer.displayPreview(for: item, revealingSensitive: true) == secret)
    }

    @Test func pasteAsTextRestoresFullDecryptedValueNotPreview() throws {
        let fullValue = String(repeating: "abc123", count: 80)
        let data = Data(fullValue.utf8)
        let item = Item(
            type: .text,
            plainTextPreview: String(fullValue.prefix(20)),
            dataBlob: EncryptionService.seal(data),
            contentHash: "hash",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            isSensitive: false,
            sizeBytes: data.count,
            isEncrypted: true
        )
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(UUID().uuidString))

        #expect(PasteboardSerializer.restore(item, to: pasteboard, asPlainText: true))
        #expect(pasteboard.string(forType: .string) == fullValue)
    }

    @Test func richTextRestoreWritesHTMLAndPlainTextFallback() throws {
        let html = "<strong>Hello</strong> <em>World</em>"
        let data = Data(html.utf8)
        let item = Item(
            type: .richText,
            plainTextPreview: "Hello World",
            dataBlob: EncryptionService.seal(data),
            contentHash: "hash",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            isSensitive: false,
            sizeBytes: data.count,
            isEncrypted: true
        )
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(UUID().uuidString))

        #expect(PasteboardSerializer.restore(item, to: pasteboard))
        #expect(pasteboard.string(forType: .html) == html)
        #expect(pasteboard.string(forType: .string)?.contains("Hello") == true)
        #expect(pasteboard.string(forType: .string)?.contains("World") == true)
    }

    @Test func sensitiveDetectorFlagsTokenLikeContent() {
        #expect(SensitiveContentDetector.looksSensitive("api_key=sk_abcdefghijklmnopqrstuvwxyz123456"))
        #expect(!SensitiveContentDetector.looksSensitive("https://example.com/docs"))
    }

    @Test func sensitiveDetectorFlagsAutoGeneratedPasswords() {
        // NordPass/1Password-style: short, no whitespace, 3+ character classes.
        #expect(SensitiveContentDetector.looksSensitive("Tx9$kP2!nQ8&mZ4@"))
        #expect(SensitiveContentDetector.looksSensitive("Pa55w0rd!Random#Mix"))
        #expect(SensitiveContentDetector.looksSensitive("hunter2!ABC"))
        // Diceware-style with spaces should NOT trip the password heuristic.
        #expect(!SensitiveContentDetector.looksSensitive("correct horse battery staple"))
    }

    @Test func sensitiveDetectorDoesNotFalsePositiveOnPlainURLsOrProse() {
        #expect(!SensitiveContentDetector.looksSensitive("https://github.com/PurpleRick/mcClippy/releases/tag/v1.0.0"))
        #expect(!SensitiveContentDetector.looksSensitive("The quick brown fox jumps over the lazy dog repeatedly to test long single-line prose"))
        // Lowercase-only or single-class is not password-like.
        #expect(!SensitiveContentDetector.looksSensitive("alllowercasenodigits"))
    }

    @Test func sensitiveDetectorFlagsGitHubAndJWT() {
        #expect(SensitiveContentDetector.looksSensitive("ghp_abcdefghijklmnopqrstuvwxyz123456"))
        #expect(SensitiveContentDetector.looksSensitive("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0In0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"))
    }

    @Test func sensitiveDetectorTightBase64() {
        // Padded base64 still flagged.
        #expect(SensitiveContentDetector.looksSensitive("YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo="))
        // Unpadded long alphanum without password complexity should NOT flag.
        // (Mixed case but no digits/specials → only 2 character classes.)
        #expect(!SensitiveContentDetector.looksSensitive("ThisIsAnExampleOfACamelCaseNameWithoutDigitsOrSpecials"))
    }

    @Test func passwordManagerBundleIDIsRecognized() {
        #expect(PasteboardSerializer.isPasswordManagerSource("com.nordsec.nordpass"))
        #expect(PasteboardSerializer.isPasswordManagerSource("com.nordvpn.macos.NordPass"))
        #expect(PasteboardSerializer.isPasswordManagerSource("com.1password.1password"))
        #expect(PasteboardSerializer.isPasswordManagerSource("com.bitwarden.desktop"))
        #expect(PasteboardSerializer.isPasswordManagerSource("com.apple.Passwords"))
        #expect(!PasteboardSerializer.isPasswordManagerSource("com.apple.Safari"))
        #expect(!PasteboardSerializer.isPasswordManagerSource(nil))
    }

    @MainActor
    @Test func shortcutSpecCodableRoundTrips() throws {
        let spec = ShortcutSpec(keyCode: 49, modifierFlags: 768)
        let data = try JSONEncoder().encode(spec)
        let decoded = try JSONDecoder().decode(ShortcutSpec.self, from: data)

        #expect(decoded == spec)
    }

    @MainActor
    @Test func shortcutRegistrationFailureExplainsConflict() {
        let spec = ShortcutSpec(keyCode: UInt32(kVK_ANSI_V), modifierFlags: UInt32(cmdKey | shiftKey))
        let status = ShortcutRegistrationStatus.failed(spec, status: OSStatus(eventHotKeyExistsErr))

        #expect(!status.isRegistered)
        #expect(status.message.contains("Could not register"))
        #expect(status.message.contains("shortcut already in use"))
        #expect(status.message.contains(spec.displayString))
    }

    @MainActor
    @Test func appExclusionsCanAddAndRemoveBundleID() {
        let id = "test.mcClippy.exclusion.\(UUID().uuidString)"
        let store = AppExclusionStore.shared

        store.add(id)
        #expect(store.isExcluded(id))

        store.remove(id)
        #expect(!store.isExcluded(id))
    }

    @MainActor
    @Test func privateModeAcknowledgesPasteboardChangesWithoutCapturingThem() throws {
        let schema = Schema([Item.self])
        let config = ModelConfiguration(schema: schema, isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: schema, configurations: [config])
        let monitor = PasteboardMonitor.shared
        let pasteboard = NSPasteboard.general
        let privateValue = "private-\(UUID().uuidString)"

        monitor.start(modelContainer: container)
        monitor.isPaused = false
        monitor.privateModeUntil = nil

        pasteboard.clearContents()
        pasteboard.setString("baseline-\(UUID().uuidString)", forType: .string)
        monitor.acknowledge(changeCount: pasteboard.changeCount)

        monitor.privateModeUntil = Date().addingTimeInterval(60)
        pasteboard.clearContents()
        pasteboard.setString(privateValue, forType: .string)
        monitor.tick()

        monitor.privateModeUntil = Date().addingTimeInterval(-1)
        monitor.tick()

        let items = try container.mainContext.fetch(FetchDescriptor<Item>())
        #expect(!items.contains { $0.plainTextPreview == privateValue })

        monitor.privateModeUntil = nil
    }

    @MainActor
    @Test func pausedMonitoringAcknowledgesPasteboardChangesWithoutCapturingThem() throws {
        let schema = Schema([Item.self])
        let config = ModelConfiguration(schema: schema, isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: schema, configurations: [config])
        let monitor = PasteboardMonitor.shared
        let pasteboard = NSPasteboard.general
        let pausedValue = "paused-\(UUID().uuidString)"

        monitor.start(modelContainer: container)
        monitor.isPaused = false
        monitor.privateModeUntil = nil

        pasteboard.clearContents()
        pasteboard.setString("baseline-\(UUID().uuidString)", forType: .string)
        monitor.acknowledge(changeCount: pasteboard.changeCount)

        monitor.isPaused = true
        pasteboard.clearContents()
        pasteboard.setString(pausedValue, forType: .string)
        monitor.tick()

        monitor.isPaused = false
        monitor.tick()

        let items = try container.mainContext.fetch(FetchDescriptor<Item>())
        #expect(!items.contains { $0.plainTextPreview == pausedValue })
    }

    @Test func retentionPolicyMapsDurations() {
        #expect(ClipboardRetentionPolicy.untilReboot.maxAgeDays == nil)
        #expect(ClipboardRetentionPolicy.forever.maxAgeDays == nil)
        #expect(ClipboardRetentionPolicy.ageLimited(days: 1) == .oneDay)
        #expect(ClipboardRetentionPolicy.ageLimited(days: 8) == .thirtyDays)
        #expect(ClipboardRetentionPolicy.ageLimited(days: 999) == .oneYear)
    }

    @Test func pasteAsTextRestoresOCRTextForImage() throws {
        let ocr = "extracted screen text"
        let item = Item(
            type: .image,
            plainTextPreview: "Image copied to clipboard",
            dataBlob: EncryptionService.seal(Data(repeating: 0, count: 8)),
            contentHash: "image-hash",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            sizeBytes: 8,
            isEncrypted: true,
            ocrText: ocr,
            ocrCompletedAt: Date()
        )
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(UUID().uuidString))

        #expect(PasteboardSerializer.restore(item, to: pasteboard, asPlainText: true))
        #expect(pasteboard.string(forType: .string) == ocr)
    }

    @Test func pasteAsTextReturnsFalseForImageWithoutOCRText() throws {
        // Image with no OCR text yet → asPlainText restore should fail
        // (so the UI can surface "Extract & Paste as Text" instead).
        let item = Item(
            type: .image,
            plainTextPreview: "Image copied to clipboard",
            dataBlob: EncryptionService.seal(Data(repeating: 0, count: 8)),
            contentHash: "image-hash-2",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            sizeBytes: 8,
            isEncrypted: true
        )
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(UUID().uuidString))
        #expect(!PasteboardSerializer.restore(item, to: pasteboard, asPlainText: true))
    }

    @MainActor
    @Test func ocrSettingsTogglePersists() {
        let settings = OCRSettings.shared
        let original = settings.isEnabled
        defer { settings.isEnabled = original }

        settings.isEnabled = false
        #expect(UserDefaults.standard.bool(forKey: "mcClippy.ocr.enabled") == false)
        settings.isEnabled = true
        #expect(UserDefaults.standard.bool(forKey: "mcClippy.ocr.enabled") == true)
    }

    @MainActor
    @Test func historySettingsClampsWithoutInfiniteRecursion() {
        // Regression: HistorySettings.maxCount.didSet self-assigned the
        // clamped value unconditionally, which retriggered didSet forever
        // and crashed the Settings panel when the stepper wrote a value.
        let settings = HistorySettings.shared
        let originalCount = settings.maxCount
        let originalBytes = settings.maxItemSizeBytes
        defer {
            settings.maxCount = originalCount
            settings.maxItemSizeBytes = originalBytes
        }

        // In-range assignments must write through without recursing.
        settings.maxCount = 50
        #expect(settings.maxCount == 50)
        settings.maxCount = 200
        #expect(settings.maxCount == 200)

        // Out-of-range values are clamped to bounds without crashing.
        settings.maxCount = 10_000
        #expect(settings.maxCount == 500)
        settings.maxCount = -50
        #expect(settings.maxCount == 10)

        // Same pattern for maxItemSizeBytes (64 KiB … 50 MiB).
        settings.maxItemSizeBytes = 5 * 1024 * 1024
        #expect(settings.maxItemSizeBytes == 5 * 1024 * 1024)
        settings.maxItemSizeBytes = 999 * 1024 * 1024
        #expect(settings.maxItemSizeBytes == 50 * 1024 * 1024)
    }

    @MainActor
    @Test func autoPasterReturnsFalseWhenTargetIsNil() {
        // Nil target → false regardless of Accessibility state.
        // (If AX is untrusted we hit the trust gate and also return false.)
        #expect(AutoPaster.paste(into: nil) == false)
    }

    @MainActor
    @Test func globalShortcutReregistersOnWakeNotification() async throws {
        let manager = GlobalShortcutManager.shared
        manager.start()
        let initialStatus = manager.registrationStatus

        // Posting the system wake notification should trigger reload().
        NSWorkspace.shared.notificationCenter.post(
            name: NSWorkspace.didWakeNotification,
            object: nil
        )
        // Let the main queue process the observer.
        try await Task.sleep(for: .milliseconds(50))

        // After reload, the status should not regress from registered.
        // (If the test host couldn't register the default shortcut initially —
        // e.g. another app already owns ⇧⌘V — we just verify the handler ran.)
        if initialStatus.isRegistered {
            #expect(manager.registrationStatus.isRegistered)
        }
    }

    @MainActor
    @Test func rebootRetentionClearsRegularAndPinnedItemsByDefault() throws {
        let settings = HistorySettings.shared
        let originalRegularRetention = settings.regularRetentionPolicy
        let originalPinnedRetention = settings.pinnedRetentionPolicy
        defer {
            settings.regularRetentionPolicy = originalRegularRetention
            settings.pinnedRetentionPolicy = originalPinnedRetention
            settings.resetRebootScopedHistoryMarkerForTesting()
        }

        settings.regularRetentionPolicy = .untilReboot
        settings.pinnedRetentionPolicy = .untilReboot
        settings.resetRebootScopedHistoryMarkerForTesting()

        let schema = Schema([Item.self])
        let config = ModelConfiguration(schema: schema, isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: schema, configurations: [config])
        let context = container.mainContext

        context.insert(Item(
            type: .text,
            plainTextPreview: "regular",
            dataBlob: Data("regular".utf8),
            contentHash: "regular",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            sizeBytes: 7
        ))
        context.insert(Item(
            type: .text,
            plainTextPreview: "pinned",
            dataBlob: Data("pinned".utf8),
            contentHash: "pinned",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            isPinned: true,
            sizeBytes: 6
        ))
        try context.save()

        PasteboardMonitor.shared.start(modelContainer: container)

        #expect(try context.fetch(FetchDescriptor<Item>()).isEmpty)
    }
}
