//
//  mcClippyTests.swift
//  mcClippyTests
//
//  Created by Gordon van Straaten on 11/05/2026.
//

import AppKit
import Foundation
import Testing
@testable import mcClippy

struct mcClippyTests {
    @Test func encryptionRoundTripsData() throws {
        let original = Data("token-value-that-should-round-trip".utf8)
        let sealed = EncryptionService.seal(original)

        #expect(sealed != nil)
        #expect(sealed.flatMap(EncryptionService.open) == original)
    }

    @Test func sensitivePreviewIsStoredAsPlaceholder() {
        let snapshot = ClipboardSnapshot(
            type: .text,
            preview: "password=correct-horse-battery-staple",
            data: Data("password=correct-horse-battery-staple".utf8),
            contentHash: "hash",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            isSensitive: true,
            sizeBytes: 37
        )

        #expect(PasteboardSerializer.storedPreview(for: snapshot) == PasteboardSerializer.sensitivePlaceholder)
    }

    @Test func revealedSensitivePreviewUsesDecryptedData() throws {
        let secret = "password=correct-horse-battery-staple"
        let data = Data(secret.utf8)
        let item = Item(
            type: .text,
            plainTextPreview: PasteboardSerializer.sensitivePlaceholder,
            dataBlob: EncryptionService.seal(data),
            contentHash: "hash",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            isSensitive: true,
            sizeBytes: data.count,
            isEncrypted: true
        )

        #expect(PasteboardSerializer.displayPreview(for: item, revealingSensitive: false) == PasteboardSerializer.sensitivePlaceholder)
        #expect(PasteboardSerializer.displayPreview(for: item, revealingSensitive: true) == secret)
    }

    @Test func pasteAsTextRestoresFullDecryptedValueNotPreview() throws {
        let fullValue = String(repeating: "abc123", count: 80)
        let data = Data(fullValue.utf8)
        let item = Item(
            type: .text,
            plainTextPreview: String(fullValue.prefix(20)),
            dataBlob: EncryptionService.seal(data),
            contentHash: "hash",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            isSensitive: false,
            sizeBytes: data.count,
            isEncrypted: true
        )
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(UUID().uuidString))

        #expect(PasteboardSerializer.restore(item, to: pasteboard, asPlainText: true))
        #expect(pasteboard.string(forType: .string) == fullValue)
    }

    @Test func richTextRestoreWritesHTMLAndPlainTextFallback() throws {
        let html = "<strong>Hello</strong> <em>World</em>"
        let data = Data(html.utf8)
        let item = Item(
            type: .richText,
            plainTextPreview: "Hello World",
            dataBlob: EncryptionService.seal(data),
            contentHash: "hash",
            sourceAppBundleId: nil,
            sourceAppName: nil,
            isSensitive: false,
            sizeBytes: data.count,
            isEncrypted: true
        )
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(UUID().uuidString))

        #expect(PasteboardSerializer.restore(item, to: pasteboard))
        #expect(pasteboard.string(forType: .html) == html)
        #expect(pasteboard.string(forType: .string)?.contains("Hello") == true)
        #expect(pasteboard.string(forType: .string)?.contains("World") == true)
    }

    @Test func sensitiveDetectorFlagsTokenLikeContent() {
        #expect(SensitiveContentDetector.looksSensitive("api_key=sk_abcdefghijklmnopqrstuvwxyz123456"))
        #expect(!SensitiveContentDetector.looksSensitive("https://example.com/docs"))
    }

    @Test func sensitiveDetectorFlagsAutoGeneratedPasswords() {
        // NordPass/1Password-style: short, no whitespace, 3+ character classes.
        #expect(SensitiveContentDetector.looksSensitive("Tx9$kP2!nQ8&mZ4@"))
        #expect(SensitiveContentDetector.looksSensitive("Pa55w0rd!Random#Mix"))
        #expect(SensitiveContentDetector.looksSensitive("hunter2!ABC"))
        // Diceware-style with spaces should NOT trip the password heuristic.
        #expect(!SensitiveContentDetector.looksSensitive("correct horse battery staple"))
    }

    @Test func sensitiveDetectorDoesNotFalsePositiveOnPlainURLsOrProse() {
        #expect(!SensitiveContentDetector.looksSensitive("https://github.com/PurpleRick/mcClippy/releases/tag/v1.0.0"))
        #expect(!SensitiveContentDetector.looksSensitive("The quick brown fox jumps over the lazy dog repeatedly to test long single-line prose"))
        // Lowercase-only or single-class is not password-like.
        #expect(!SensitiveContentDetector.looksSensitive("alllowercasenodigits"))
    }

    @Test func sensitiveDetectorFlagsGitHubAndJWT() {
        #expect(SensitiveContentDetector.looksSensitive("ghp_abcdefghijklmnopqrstuvwxyz123456"))
        #expect(SensitiveContentDetector.looksSensitive("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0In0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"))
    }

    @Test func sensitiveDetectorTightBase64() {
        // Padded base64 still flagged.
        #expect(SensitiveContentDetector.looksSensitive("YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo="))
        // Unpadded long alphanum without password complexity should NOT flag.
        // (Mixed case but no digits/specials → only 2 character classes.)
        #expect(!SensitiveContentDetector.looksSensitive("ThisIsAnExampleOfACamelCaseNameWithoutDigitsOrSpecials"))
    }

    @Test func passwordManagerBundleIDIsRecognized() {
        #expect(PasteboardSerializer.isPasswordManagerSource("com.nordsec.nordpass"))
        #expect(PasteboardSerializer.isPasswordManagerSource("com.nordvpn.macos.NordPass"))
        #expect(PasteboardSerializer.isPasswordManagerSource("com.1password.1password"))
        #expect(PasteboardSerializer.isPasswordManagerSource("com.bitwarden.desktop"))
        #expect(PasteboardSerializer.isPasswordManagerSource("com.apple.Passwords"))
        #expect(!PasteboardSerializer.isPasswordManagerSource("com.apple.Safari"))
        #expect(!PasteboardSerializer.isPasswordManagerSource(nil))
    }

    @MainActor
    @Test func shortcutSpecCodableRoundTrips() throws {
        let spec = ShortcutSpec(keyCode: 49, modifierFlags: 768)
        let data = try JSONEncoder().encode(spec)
        let decoded = try JSONDecoder().decode(ShortcutSpec.self, from: data)

        #expect(decoded == spec)
    }

    @MainActor
    @Test func appExclusionsCanAddAndRemoveBundleID() {
        let id = "test.mcClippy.exclusion.\(UUID().uuidString)"
        let store = AppExclusionStore.shared

        store.add(id)
        #expect(store.isExcluded(id))

        store.remove(id)
        #expect(!store.isExcluded(id))
    }

    @MainActor
    @Test func historySettingsClampValues() {
        let settings = HistorySettings.shared
        let originalCount = settings.maxCount
        let originalSize = settings.maxItemSizeBytes
        let originalAge = settings.maxAgeDays

        settings.maxCount = 1
        settings.maxItemSizeBytes = 1
        settings.maxAgeDays = 999

        #expect(settings.maxCount == 10)
        #expect(settings.maxItemSizeBytes == 64 * 1024)
        #expect(settings.maxAgeDays == 365)

        settings.maxCount = originalCount
        settings.maxItemSizeBytes = originalSize
        settings.maxAgeDays = originalAge
    }
}
